/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kasirbaju;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author MDafi
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    private String nikAdmin;
    private String nikKaryawan;
    private String namaAdmin;
    private String namaKaryawan;
    private String jabatanAdmin;
    private String jabatanKaryawan;
    private String jabatannya;
    
    KoneksiDB kdb = new KoneksiDB();
    
    public Login() {
        initComponents();
         Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
         System.out.println(screenSize);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void mouseEnteredExitedReleasedPanelKiri(JLabel label, String tujuan, String pilihan){
        if(tujuan.equalsIgnoreCase("Entered")){
            label.setForeground(new Color(242, 37, 200));
            
        }
        if(tujuan.equalsIgnoreCase("Exited")){
            label.setForeground(new Color(150,114,182));
            
        }
        if(tujuan.equalsIgnoreCase("Released")){
            
            if(pilihan.equalsIgnoreCase("Masuk")){
                dashboard dashB = new dashboard();
                dashB.setVisible(true);
                int state = dashB.getExtendedState();
                state &= ~JFrame.ICONIFIED;
                dashB.setExtendedState(state);
                dashB.setAlwaysOnTop(true);
                dashB.toFront();
                dashB.requestFocus();
                dashB.setAlwaysOnTop(false);
                this.dispose();
                
            } else if(pilihan.equalsIgnoreCase("Keluar")) {
                System.exit(0);
            }
            
        
        this.dispose();
        }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackgroundPanel = new javax.swing.JPanel();
        PanelLoginForm = new javax.swing.JPanel();
        LogoMrMeat = new javax.swing.JLabel();
        JudulLabel = new javax.swing.JLabel();
        JudulLabel1 = new javax.swing.JLabel();
        NIKLabel = new javax.swing.JLabel();
        KataSandiLabel = new javax.swing.JLabel();
        MasukLabel = new javax.swing.JLabel();
        Keluar = new javax.swing.JLabel();
        KataSandiTextField = new javax.swing.JPasswordField();
        eye = new javax.swing.JPanel();
        eye1 = new javax.swing.JLabel();
        eye2 = new javax.swing.JLabel();
        BackGroundLoginForm = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BackgroundPanel.setOpaque(false);
        BackgroundPanel.setPreferredSize(new java.awt.Dimension(1366, 768));
        BackgroundPanel.setLayout(null);

        LogoMrMeat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/rsz_mr_meat_glow_logo.png"))); // NOI18N

        JudulLabel.setBackground(new java.awt.Color(255, 255, 255));
        JudulLabel.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        JudulLabel.setForeground(new java.awt.Color(204, 204, 204));
        JudulLabel.setText("LOGIN");

        JudulLabel1.setBackground(new java.awt.Color(255, 255, 255));
        JudulLabel1.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        JudulLabel1.setForeground(new java.awt.Color(242, 37, 200));
        JudulLabel1.setText("FORM");

        NIKLabel.setBackground(new java.awt.Color(255, 255, 255));
        NIKLabel.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        NIKLabel.setForeground(new java.awt.Color(255, 255, 255));
        NIKLabel.setText("NIK :");
        NIKLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        NIKTextField.setBackground(new java.awt.Color(51, 0, 97));
        NIKTextField.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        NIKTextField.setForeground(new java.awt.Color(255, 255, 255));
        NIKTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(150, 114, 182), 2));
        NIKTextField.setCaretColor(new java.awt.Color(255, 255, 255));
        NIKTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        NIKTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NIKTextFieldActionPerformed(evt);
            }
        });

        KataSandiLabel.setBackground(new java.awt.Color(255, 255, 255));
        KataSandiLabel.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        KataSandiLabel.setForeground(new java.awt.Color(255, 255, 255));
        KataSandiLabel.setText("Kata Sandi :");
        KataSandiLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        MasukLabel.setBackground(new java.awt.Color(51, 0, 97));
        MasukLabel.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        MasukLabel.setForeground(new java.awt.Color(150, 114, 182));
        MasukLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-enter-45.png"))); // NOI18N
        MasukLabel.setText("Masuk");
        MasukLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 37, 200), 2));
        MasukLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MasukLabel.setOpaque(true);
        MasukLabel.setPreferredSize(new java.awt.Dimension(136, 45));
        MasukLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MasukLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MasukLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MasukLabelMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                MasukLabelMouseReleased(evt);
            }
        });

        Keluar.setBackground(new java.awt.Color(51, 0, 97));
        Keluar.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        Keluar.setForeground(new java.awt.Color(150, 114, 182));
        Keluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-exit-45.png"))); // NOI18N
        Keluar.setText("Keluar");
        Keluar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 37, 200), 2));
        Keluar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Keluar.setOpaque(true);
        Keluar.setPreferredSize(new java.awt.Dimension(136, 45));
        Keluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KeluarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                KeluarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                KeluarMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                KeluarMouseReleased(evt);
            }
        });

        KataSandiTextField.setBackground(new java.awt.Color(51, 0, 97));
        KataSandiTextField.setForeground(new java.awt.Color(255, 255, 255));
        KataSandiTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(150, 114, 182), 2));

        eye.setBackground(new java.awt.Color(51, 0, 97));
        eye.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(150, 114, 182), 2));
        eye.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eye.setLayout(null);

        eye1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-eye-unchecked-30.png"))); // NOI18N
        eye1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eye1MouseClicked(evt);
            }
        });
        eye.add(eye1);
        eye1.setBounds(0, 0, 30, 30);

        eye2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-eye-checked-30.png"))); // NOI18N
        eye2.setVisible(false);
        eye2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eye2MouseClicked(evt);
            }
        });
        eye.add(eye2);
        eye2.setBounds(0, 0, 30, 30);

        javax.swing.GroupLayout PanelLoginFormLayout = new javax.swing.GroupLayout(PanelLoginForm);
        PanelLoginForm.setLayout(PanelLoginFormLayout);
        PanelLoginFormLayout.setHorizontalGroup(
            PanelLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLoginFormLayout.createSequentialGroup()
                .addGroup(PanelLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLoginFormLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(LogoMrMeat))
                    .addGroup(PanelLoginFormLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(PanelLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NIKLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NIKTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelLoginFormLayout.createSequentialGroup()
                                .addComponent(JudulLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JudulLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelLoginFormLayout.createSequentialGroup()
                                .addComponent(MasukLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(KataSandiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelLoginFormLayout.createSequentialGroup()
                                .addComponent(KataSandiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(eye, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(62, 62, Short.MAX_VALUE))
        );
        PanelLoginFormLayout.setVerticalGroup(
            PanelLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLoginFormLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LogoMrMeat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JudulLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JudulLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NIKLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NIKTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLoginFormLayout.createSequentialGroup()
                        .addComponent(KataSandiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(KataSandiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(eye, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(PanelLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MasukLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Keluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        BackgroundPanel.add(PanelLoginForm);
        PanelLoginForm.setBounds(550, 120, 300, 485);
        PanelLoginForm.setBackground(new Color(68, 30, 92,128));

        BackGroundLoginForm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/rsz_2861 (2).jpg"))); // NOI18N
        BackGroundLoginForm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 97), 4));
        BackgroundPanel.add(BackGroundLoginForm);
        BackGroundLoginForm.setBounds(550, 120, 300, 485);

        getContentPane().add(BackgroundPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dashboardblur.v1 (3).jpg"))); // NOI18N
        Background.setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void NIKTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NIKTextFieldActionPerformed
        // TODO add your handling code here:
        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/newposs","root","");
            String Sql = "SELECT * FROM akun where NIK = '"+NIKTextField.getText()+"' and KataSandi = '"+String.valueOf(KataSandiTextField.getPassword())+"'";

            Statement S = con.createStatement();
            ResultSet r = S.executeQuery(Sql);
            System.out.println(Sql);
                if (r.next()){
                    System.out.println("OK");

                    this.dispose();
                    //dashboard.name2.setText(rs.getString(2));
                    
                    mouseEnteredExitedReleasedPanelKiri(MasukLabel, "Released", "Masuk");
                }
                else{
                    JOptionPane.showMessageDialog(this, "EMAIL ATAU PASSWORD SALAH ATAU BELUM TERISI");
                }
        }   catch (SQLException ex) {
                System.out.println(ex.getMessage());
                JOptionPane.showMessageDialog(this, "KONEKSI GAGAL");
            } catch (ClassNotFoundException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_NIKTextFieldActionPerformed

    private void KeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KeluarMouseClicked
         
    }//GEN-LAST:event_KeluarMouseClicked

    private void KeluarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KeluarMouseEntered
        // TODO add your handling code here:
        mouseEnteredExitedReleasedPanelKiri(Keluar, "Entered", "Keluar");
    }//GEN-LAST:event_KeluarMouseEntered

    private void KeluarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KeluarMouseExited
        // TODO add your handling code here:
        mouseEnteredExitedReleasedPanelKiri(Keluar, "Exited", "Keluar");
    }//GEN-LAST:event_KeluarMouseExited

    private void MasukLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MasukLabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_MasukLabelMouseClicked

    private void MasukLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MasukLabelMouseEntered
        // TODO add your handling code here:
        mouseEnteredExitedReleasedPanelKiri(MasukLabel, "Entered", "Masuk");
    }//GEN-LAST:event_MasukLabelMouseEntered

    private void MasukLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MasukLabelMouseExited
        // TODO add your handling code here:
        mouseEnteredExitedReleasedPanelKiri(MasukLabel, "Exited", "Masuk");
    }//GEN-LAST:event_MasukLabelMouseExited

    private void MasukLabelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MasukLabelMouseReleased
        // TODO add your handling code here:
        
        
        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/newposs","root","");
            String Sql = "SELECT * FROM akun where NIK = '"+NIKTextField.getText()+"' and KataSandi = '"+String.valueOf(KataSandiTextField.getPassword())+"'";

            Statement S = con.createStatement();
            ResultSet r = S.executeQuery(Sql);
            System.out.println(Sql);
                if (r.next()){
                    
                    System.out.println("OK");

                    this.dispose();
               
                    inheritanceAll operan = new inheritanceAll();
                    
                      nikKaryawan = r.getString(1);
                      jabatanKaryawan = r.getString(2);
                      namaKaryawan = r.getString(3);
                      
                      
                      operan.setNik(nikKaryawan);
                      operan.setJabatan(jabatanKaryawan);
                      operan.setNama(namaKaryawan);
                    
                    mouseEnteredExitedReleasedPanelKiri(MasukLabel, "Released", "Masuk");
                }
                else{
                    JOptionPane.showMessageDialog(this, "EMAIL ATAU PASSWORD SALAH ATAU BELUM TERISI");
                }
        }   catch (SQLException ex) {
                System.out.println(ex.getMessage());
                JOptionPane.showMessageDialog(this, "KONEKSI GAGAL");
            } catch (ClassNotFoundException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_MasukLabelMouseReleased

    private void KeluarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KeluarMouseReleased
        // TODO add your handling code here:
        mouseEnteredExitedReleasedPanelKiri(Keluar, "Released", "Keluar");
    }//GEN-LAST:event_KeluarMouseReleased

    private void eye1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eye1MouseClicked
        // TODO add your handling code here:
        eye2.setVisible(true);
        eye1.setVisible(false);
        KataSandiTextField.setEchoChar((char)0);
    }//GEN-LAST:event_eye1MouseClicked

    private void eye2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eye2MouseClicked
        // TODO add your handling code here:
        eye2.setVisible(false);
        eye1.setVisible(true);
        KataSandiTextField.setEchoChar('*');
    }//GEN-LAST:event_eye2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackGroundLoginForm;
    private javax.swing.JLabel Background;
    private javax.swing.JPanel BackgroundPanel;
    private javax.swing.JLabel JudulLabel;
    private javax.swing.JLabel JudulLabel1;
    private javax.swing.JLabel KataSandiLabel;
    private javax.swing.JPasswordField KataSandiTextField;
    private javax.swing.JLabel Keluar;
    private javax.swing.JLabel LogoMrMeat;
    private javax.swing.JLabel MasukLabel;
    private javax.swing.JLabel NIKLabel;
    public static final javax.swing.JTextField NIKTextField = new javax.swing.JTextField();
    private javax.swing.JPanel PanelLoginForm;
    private javax.swing.JPanel eye;
    private javax.swing.JLabel eye1;
    private javax.swing.JLabel eye2;
    // End of variables declaration//GEN-END:variables
}
