/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kasirbaju;

import com.itextpdf.text.pdf.PdfDocument;
import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static kasirbaju.PanelPersediaan.HargaTextField;
import static kasirbaju.PanelPersediaan.NamaProdukTextField;
import java.util.*;
import javax.swing.JFrame;
import java.io.*;
import static java.lang.System.*;

import java.io.FileWriter;
import java.io.IOException;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Color;
import javax.print.Doc;
import javax.print.DocFlavor;
import javax.print.DocPrintJob;
import javax.print.PrintException;
import javax.print.PrintService;
import javax.print.PrintServiceLookup;
import javax.print.SimpleDoc;
import javax.print.attribute.HashPrintRequestAttributeSet;
import javax.print.attribute.PrintRequestAttributeSet;
import static kasirbaju.PanelPersediaan.JenisTextField;
import static kasirbaju.PanelPersediaan.PersediaanTextField;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;


/**
 *
 * @author MDafi
 */
public class PanelKasir extends javax.swing.JFrame {

    /**
     * Creates new form PanelKasir
     */
    private static KoneksiDB kdb = new KoneksiDB();
        Connection con;
    PreparedStatement pst;
    DefaultTableModel model;
    private static LihatPersediaan LPP;
    
    public PanelKasir() {
        initComponents();
         LPP = new LihatPersediaan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
     public void openCashDrawer(byte[] open) {

        PrintService pservice = PrintServiceLookup.lookupDefaultPrintService(); 
        DocPrintJob job = pservice.createPrintJob();
        DocFlavor flavor = DocFlavor.BYTE_ARRAY.AUTOSENSE;
        Doc doc = new SimpleDoc(open,flavor,null);
        PrintRequestAttributeSet aset = new 
        HashPrintRequestAttributeSet();
        try {
            job.print(doc, aset);
        } catch (PrintException ex) {
            System.out.println(ex.getMessage());
        }
        
    }
     
    public void printBill() {
        
        if("".equalsIgnoreCase(txtbill.getText())){
            JOptionPane.showMessageDialog(this, "Jualah barang terlebih dahulu","Error",JOptionPane.WARNING_MESSAGE);
        }else {
            PrinterService printerService = new PrinterService();

            System.out.println(printerService.getPrinters());
            printerService.printString("Pos58 Printer", "\n\n" + txtbill.getText());
            printerService.printString("Pos58 Printer", "\n\n\n\n\n\n");

            // cut that paper!
            byte[] cutP = new byte[] { 0x1d, 'V', 1 };
            byte[] open = {27,112,0,100,(byte) 250};

            printerService.printBytes("Pos58 Printer", cutP);
            openCashDrawer(open);
            
            Date dNow = new Date( );
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH-mm-ss") ;
            String nama = dateFormat.format(dNow);
            String lokasi = dateFormat.format(dNow)+".pdf";
            
            Document document = new Document();
            String FILE = "D:/Data/"+lokasi;
            try
            {
                PdfWriter writer = PdfWriter.getInstance(document, new FileOutputStream(FILE));
                document.open();
                document.add(new Paragraph(txtbill.getText()));

                //Set attributes here
                document.addAuthor("Newposs");
                document.addCreationDate();
                document.addCreator("Mr.Meat");
                document.addTitle("Struk");
                document.addSubject(nama);

                document.close();
                writer.close();
            } catch (Exception e)
            {
                e.printStackTrace();
            }
            JOptionPane.showMessageDialog(this, "Berhasil cetak struk ","Informasi",JOptionPane.INFORMATION_MESSAGE);   
        }
    }
    
     public static String insertString( String originalString, String stringToBeInserted, int index){ 
  
        // Create a new string 
        String newString = new String(); 
  
        for (int i = 0; i < originalString.length(); i++) { 
  
            // Insert the original string character 
            // into the new string 
            newString += originalString.charAt(i); 
  
            if (i == index) { 
  
                // Insert the string to be inserted 
                // into the new string 
                newString += stringToBeInserted; 
            } 
        } 
  
        // return the modified String 
        return newString; 
    }
    
    public void bill() {
        
        int row = jTable1.getRowCount();
        
        int id = 0;
        String namaProduk = "";
        String jenis = "";
        String satuan = "";
        int harga = 0;
        int jumlah = 0;
        int jumlahWords = 0;
        String tampilConditional = "";
        
        
        
        Date dNow = new Date( );
        SimpleDateFormat ft = new SimpleDateFormat ("E dd.MM.yyyy 'at' hh:mm:ss a ");


        String total = Total2Label.getText();
        DefaultTableModel model = new DefaultTableModel();
        model = (DefaultTableModel)jTable1.getModel(); 
        
        DecimalFormat kursIndonesia = (DecimalFormat) DecimalFormat.getCurrencyInstance();
        DecimalFormatSymbols formatRp = new DecimalFormatSymbols();

        formatRp.setCurrencySymbol("Rp. ");
        formatRp.setMonetaryDecimalSeparator(',');
        formatRp.setGroupingSeparator('.');

        kursIndonesia.setDecimalFormatSymbols(formatRp);
//        System.out.printf("Hargaah: %s %n", kursIndonesia.format(harga));
        
        if(row > 0){
                //print some stuff. Change the printer name to your thermal printer name.
            txtbill.setText(txtbill.getText() + "              MR.MEAT           \n\n");
            txtbill.setText(txtbill.getText() + " JL.Bisma Tengah 2 Blok C5 No.22");
            txtbill.setText(txtbill.getText() + "         Taman Sunter Agung \n");
            txtbill.setText(txtbill.getText() + "           Jakarta Utara\n");
            txtbill.setText(txtbill.getText() + "     TEL : 0813 732 983 40      \n");
            txtbill.setText(txtbill.getText() + "********************************\n");
            txtbill.setText(txtbill.getText() + "            POSBILL             \n");
            //txtbill.setFont(txtbill.getFont().deriveFont(Font.PLAIN, 15));
            txtbill.setText(txtbill.getText() + "********************************\n");   
            txtbill.setText(txtbill.getText() + ft.format(dNow) +"\n\n");
            //Heading
            for(int i = 0; i < model.getRowCount(); i++){              
                    id = (Integer) jTable1.getValueAt(i, 0);
                    namaProduk = (String) jTable1.getValueAt(i, 1);
                    jenis = (String)jTable1.getValueAt(i, 2);
                    satuan = (String)jTable1.getValueAt(i, 3);
                    harga = (Integer)jTable1.getValueAt(i, 4);
                    jumlah = (Integer)jTable1.getValueAt(i, 5);
                    String kg = "";
                    int hargaawalTampil =  harga;
                    int hargaKalkulasiTampil =  harga*  jumlah;
                String pcrp = "x";
                String pork = "";
                if(satuan.equalsIgnoreCase("Gram")){
                    kg = "/kg";
                    hargaawalTampil = harga*1000;
                    pork = "gr";
                }else if(satuan.equalsIgnoreCase("Pack")) {
                    kg = "/Pack";
                    hargaawalTampil = harga;
                    pork = " Pack";
                }
                    txtbill.setText(txtbill.getText() + namaProduk + " " + jenis +"\n");
                    tampilConditional = hargaawalTampil + kg + " " + pcrp+jumlah+pork + " " + hargaKalkulasiTampil  + "\n";  
                    jumlahWords = tampilConditional.length();
                    System.out.println("jumlah word"+jumlahWords);
                    if(jumlahWords >=32){
                        txtbill.setText(txtbill.getText() + insertString(tampilConditional,"\n",30));
                    }else {
                        txtbill.setText(txtbill.getText() + tampilConditional);
                    }
                   
                    
            }   
            txtbill.setText(txtbill.getText() + "\n");
                    tampilConditional = kursIndonesia.format(Double.parseDouble(total)) + "\n";
                    jumlahWords = tampilConditional.length();
                    System.out.println("jumlah word"+jumlahWords);
                    if(jumlahWords >=35){
                        txtbill.setText(txtbill.getText() + "Total Belanja : " + insertString(tampilConditional,"\n",33));
                    }else {
                        txtbill.setText(txtbill.getText() + "Total Belanja : " + tampilConditional);
                    }
            txtbill.setText(txtbill.getText() + "\n");
            txtbill.setText(txtbill.getText() + "********************************\n");
            txtbill.setText(txtbill.getText() + "  No.REK :  5820 3974 03 (BCA)  \n");
            txtbill.setText(txtbill.getText() + "     THANK YOU,COME AGAIN       \n");
            
           jual(id, namaProduk, jenis, harga, jumlah); 
        }else {
            JOptionPane.showMessageDialog(this, "Tidak ada yang dijual","Error",JOptionPane.WARNING_MESSAGE);
        }
        
        
        
    }
    
    public void jual(int id, String namaProduk, String jenis, int harga, int jumlah) {
        
        int row = jTable1.getRowCount();
        
        
        for (int j = 0; j  < row; j++) {
           
                id = (Integer) jTable1.getValueAt(j, 0);
                namaProduk = (String) jTable1.getValueAt(j, 1);
                jenis = (String) jTable1.getValueAt(j, 2);
                harga = (Integer) jTable1.getValueAt(j, 4);
                jumlah = (Integer) jTable1.getValueAt(j, 5);
            
            try {
                    Class.forName("com.mysql.cj.jdbc.Driver");
                    con = DriverManager.getConnection("jdbc:mysql://localhost/newposs","root","");
                       
                        
                    PreparedStatement pst;
                    
                    Statement S;
                    ResultSet r = null;
                    int persediaan = 0;
                    
                    String SQLcari = "SELECT * FROM stock WHERE NamaProduk = ? AND Jenis = ? ";
                    pst = con.prepareStatement(SQLcari);
                    pst.setString(1, namaProduk);
                    pst.setString(2, jenis);
                    r = pst.executeQuery();
                    while (r.next()){
                        persediaan = Integer.parseInt(r.getString(6));
                        persediaan = persediaan - jumlah;
                        System.out.println("Gram : "+persediaan);
                    }
                    
                    
                    
                    String aSQL = "UPDATE stock SET `Persediaan`='"+Integer.toString(persediaan)+"' WHERE `NamaProduk`='"+namaProduk+"' AND `Jenis`='"+jenis+"'";
                    System.out.println("aSQL : "+jumlah);
                    S = con.createStatement();
                    int R = S.executeUpdate(aSQL);
                    
                    

                } catch(Exception t){
                        t.printStackTrace();
                        JOptionPane.showMessageDialog(null, "data gagal dijual");
                }
            
        }JOptionPane.showMessageDialog(this, "BERHASIL Di Jual ");
                    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                    model.setRowCount(0);
                    Total2Label.setText("");
        
    }
    
    public void cari(boolean kunci1, boolean kunci2){
        
        if(kunci1 && kunci2){
            try {
                    Class.forName("com.mysql.cj.jdbc.Driver");
                        con = DriverManager.getConnection("jdbc:mysql://localhost/newposs","root","");
                       
                        String namaProduk = NamaProdukTextField.getText();
                        String jenis = JenisTextField.getText();

                        pst = con.prepareStatement("SELECT * FROM stock WHERE NamaProduk = ? AND Jenis = ?");
                        pst.setString(1, namaProduk);
                        pst.setString(2, jenis);
                        ResultSet rs = pst.executeQuery();
                        if(rs.next()==true)
                        {
                            String idDB = rs.getString(1);
                            String satuanDB = rs.getString(5);
                            String hargaDB = rs.getString(7);
                            IdTextField.setText(idDB);
                            SatuanTextField.setText(satuanDB);
                            HargaTextField.setText(hargaDB);

                        }   
                        else
                        {
                            IdTextField.setText("");
                            SatuanTextField.setText("");
                            HargaTextField.setText("");
                        }

                        } catch (SQLException ex) {

                        } catch (ClassNotFoundException ex) {
                            Logger.getLogger(PanelKasir.class.getName()).log(Level.SEVERE, null, ex);
                        }
            
        }
        
         

    }
    public void tambahList(){
        if("".equals(IdTextField.getText())||"".equals(NamaProdukTextField.getText())||"".equalsIgnoreCase(JenisTextField.getText())||"".equals(SatuanTextField.getText())||"".equals(JumlahTextField.getText())||"".equals(HargaTextField.getText())){
            System.out.println(IdTextField.getText());    
             System.out.println(NamaProdukTextField.getText());    
              System.out.println(JenisTextField.getText());
              System.out.println(SatuanTextField.getText());
              System.out.println(JumlahTextField.getText());  
               System.out.println(HargaTextField.getText());    
                
                 
            
            
            
            JOptionPane.showMessageDialog(this, "DATA TIDAK VALID","Error",JOptionPane.WARNING_MESSAGE);
            }else {
                if(!"".equals(IdTextField.getText())&&!"".equals(NamaProdukTextField.getText())&&!"".equalsIgnoreCase(JenisTextField.getText())&&!"".equals(SatuanTextField.getText())&&!"".equals(JumlahTextField.getText())&&!"".equals(HargaTextField.getText())){
                    
                    int id = Integer.parseInt(IdTextField.getText());
                    String namaProduk = (NamaProdukTextField.getText());
                    String jenis = JenisTextField.getText();
                    String satuan = SatuanTextField.getText();
                    int harga = Integer.parseInt(HargaTextField.getText());
                    int jumlah = Integer.parseInt(JumlahTextField.getText());
                    int total = jumlah * harga;

                    model = (DefaultTableModel)jTable1.getModel();

                    model.addRow(new Object[]
                            {
                                id,
                                namaProduk,
                                jenis,
                                satuan,
                                harga,
                                jumlah,
                                total,

                            });

                    int sum = 0;

                    for(int i = 0; i<jTable1.getRowCount(); i++)
                        {
                            sum = sum + Integer.parseInt(jTable1.getValueAt(i, 6).toString());
                        }

                    Total2Label.setText(Integer.toString(sum));

                    IdTextField.setText("");
                    NamaProdukTextField.setText("");
                    JenisTextField.setText("");
                    SatuanTextField.setText("");
                    HargaTextField.setText("");
                    JumlahTextField.setText("");

                }else {
                    System.out.println("gagal");
                }
        }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackGround = new javax.swing.JPanel();
        JudulLabel1 = new javax.swing.JLabel();
        JudulLabel2 = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        MenuPanel = new javax.swing.JPanel();
        TotalLabel2 = new javax.swing.JLabel();
        IdLabel = new javax.swing.JLabel();
        NamaProdukLabel = new javax.swing.JLabel();
        JenisLabel = new javax.swing.JLabel();
        SatuanLabel = new javax.swing.JLabel();
        JumlahLabel = new javax.swing.JLabel();
        HargaLabel = new javax.swing.JLabel();
        TambahKeListLabel = new javax.swing.JLabel();
        TotalLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtbill = new javax.swing.JTextArea();
        HapusLabel = new javax.swing.JLabel();
        JualLabel = new javax.swing.JLabel();
        CetakStrukLabel = new javax.swing.JLabel();
        TotalLabel = new javax.swing.JLabel();
        RPLabel = new javax.swing.JLabel();
        Total2Label = new javax.swing.JLabel();
        KeluarLabel1 = new javax.swing.JLabel();
        KeluarLabel = new javax.swing.JLabel();
        MenuSemuaLabel1 = new javax.swing.JLabel();
        BackGroundIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BackGround.setOpaque(false);
        BackGround.setPreferredSize(new java.awt.Dimension(1366, 768));
        BackGround.setLayout(null);

        JudulLabel1.setBackground(new java.awt.Color(255, 255, 255));
        JudulLabel1.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        JudulLabel1.setForeground(new java.awt.Color(204, 204, 204));
        JudulLabel1.setText("PANEL");
        BackGround.add(JudulLabel1);
        JudulLabel1.setBounds(30, 30, 90, 50);

        JudulLabel2.setBackground(new java.awt.Color(255, 255, 255));
        JudulLabel2.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        JudulLabel2.setForeground(new java.awt.Color(255, 255, 255));
        JudulLabel2.setText("KASIR");
        BackGround.add(JudulLabel2);
        JudulLabel2.setBounds(120, 30, 80, 50);

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-cash-register-70.png"))); // NOI18N
        BackGround.add(Logo);
        Logo.setBounds(200, 10, 70, 70);

        MenuPanel.setBackground(new java.awt.Color(148, 112, 189));
        MenuPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 37, 200), 2));
        MenuPanel.setForeground(new java.awt.Color(204, 204, 204));
        MenuPanel.setOpaque(false);
        MenuPanel.setPreferredSize(new java.awt.Dimension(100, 50));
        MenuPanel.setLayout(null);

        TotalLabel2.setBackground(new java.awt.Color(255, 255, 255));
        TotalLabel2.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        TotalLabel2.setForeground(new java.awt.Color(255, 255, 255));
        TotalLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TotalLabel2.setText("INPUT");
        TotalLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        MenuPanel.add(TotalLabel2);
        TotalLabel2.setBounds(0, 0, 200, 30);

        IdLabel.setBackground(new java.awt.Color(255, 255, 255));
        IdLabel.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        IdLabel.setForeground(new java.awt.Color(255, 255, 255));
        IdLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IdLabel.setText("Id");
        IdLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        MenuPanel.add(IdLabel);
        IdLabel.setBounds(0, 40, 200, 30);

        IdTextField.setFont(new java.awt.Font("Myriad Pro", 0, 24)); // NOI18N
        IdTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(117, 84, 155), 2));
        IdTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        IdTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdTextFieldActionPerformed(evt);
            }
        });
        IdTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                IdTextFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                IdTextFieldKeyReleased(evt);
            }
        });
        MenuPanel.add(IdTextField);
        IdTextField.setBounds(20, 70, 160, 30);

        NamaProdukLabel.setBackground(new java.awt.Color(255, 255, 255));
        NamaProdukLabel.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        NamaProdukLabel.setForeground(new java.awt.Color(255, 255, 255));
        NamaProdukLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NamaProdukLabel.setText("Nama Produk");
        NamaProdukLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        MenuPanel.add(NamaProdukLabel);
        NamaProdukLabel.setBounds(0, 110, 200, 30);

        NamaProdukTextField.setFont(new java.awt.Font("Myriad Pro", 0, 24)); // NOI18N
        NamaProdukTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(117, 84, 155), 2));
        NamaProdukTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        NamaProdukTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaProdukTextFieldActionPerformed(evt);
            }
        });
        NamaProdukTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NamaProdukTextFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                NamaProdukTextFieldKeyReleased(evt);
            }
        });
        MenuPanel.add(NamaProdukTextField);
        NamaProdukTextField.setBounds(20, 140, 160, 30);

        JenisLabel.setBackground(new java.awt.Color(255, 255, 255));
        JenisLabel.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        JenisLabel.setForeground(new java.awt.Color(255, 255, 255));
        JenisLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JenisLabel.setText("Jenis");
        JenisLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        MenuPanel.add(JenisLabel);
        JenisLabel.setBounds(0, 190, 200, 30);

        JenisTextField.setFont(new java.awt.Font("Myriad Pro", 0, 24)); // NOI18N
        JenisTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(117, 84, 155), 2));
        JenisTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        JenisTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JenisTextFieldActionPerformed(evt);
            }
        });
        JenisTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JenisTextFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JenisTextFieldKeyReleased(evt);
            }
        });
        MenuPanel.add(JenisTextField);
        JenisTextField.setBounds(20, 220, 160, 30);

        SatuanLabel.setBackground(new java.awt.Color(255, 255, 255));
        SatuanLabel.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        SatuanLabel.setForeground(new java.awt.Color(255, 255, 255));
        SatuanLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SatuanLabel.setText("Satuan");
        SatuanLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        MenuPanel.add(SatuanLabel);
        SatuanLabel.setBounds(0, 270, 200, 30);

        SatuanTextField.setFont(new java.awt.Font("Myriad Pro", 0, 24)); // NOI18N
        SatuanTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(117, 84, 155), 2));
        SatuanTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        SatuanTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SatuanTextFieldActionPerformed(evt);
            }
        });
        SatuanTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SatuanTextFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SatuanTextFieldKeyReleased(evt);
            }
        });
        MenuPanel.add(SatuanTextField);
        SatuanTextField.setBounds(20, 300, 160, 30);

        JumlahLabel.setBackground(new java.awt.Color(255, 255, 255));
        JumlahLabel.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        JumlahLabel.setForeground(new java.awt.Color(255, 255, 255));
        JumlahLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JumlahLabel.setText("Jumlah");
        JumlahLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        MenuPanel.add(JumlahLabel);
        JumlahLabel.setBounds(0, 430, 200, 30);

        JumlahTextField.setFont(new java.awt.Font("Myriad Pro", 0, 24)); // NOI18N
        JumlahTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(117, 84, 155), 2));
        JumlahTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        JumlahTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JumlahTextFieldActionPerformed(evt);
            }
        });
        JumlahTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JumlahTextFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JumlahTextFieldKeyReleased(evt);
            }
        });
        MenuPanel.add(JumlahTextField);
        JumlahTextField.setBounds(20, 470, 160, 30);

        HargaLabel.setBackground(new java.awt.Color(255, 255, 255));
        HargaLabel.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        HargaLabel.setForeground(new java.awt.Color(255, 255, 255));
        HargaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HargaLabel.setText("Harga");
        HargaLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        MenuPanel.add(HargaLabel);
        HargaLabel.setBounds(0, 350, 200, 30);

        HargaTextField.setFont(new java.awt.Font("Myriad Pro", 0, 24)); // NOI18N
        HargaTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(117, 84, 155), 2));
        HargaTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        HargaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HargaTextFieldActionPerformed(evt);
            }
        });
        HargaTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                HargaTextFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                HargaTextFieldKeyReleased(evt);
            }
        });
        MenuPanel.add(HargaTextField);
        HargaTextField.setBounds(20, 380, 160, 30);

        TambahKeListLabel.setBackground(new java.awt.Color(51, 0, 97));
        TambahKeListLabel.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        TambahKeListLabel.setForeground(new java.awt.Color(255, 255, 255));
        TambahKeListLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TambahKeListLabel.setText("TAMBAH KE LIST");
        TambahKeListLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(242, 37, 200), 2, true));
        TambahKeListLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TambahKeListLabel.setOpaque(true);
        TambahKeListLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TambahKeListLabelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TambahKeListLabelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TambahKeListLabelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                TambahKeListLabelMouseReleased(evt);
            }
        });
        MenuPanel.add(TambahKeListLabel);
        TambahKeListLabel.setBounds(10, 510, 180, 70);

        BackGround.add(MenuPanel);
        MenuPanel.setBounds(30, 90, 200, 600);

        TotalLabel1.setBackground(new java.awt.Color(255, 255, 255));
        TotalLabel1.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        TotalLabel1.setForeground(new java.awt.Color(255, 255, 255));
        TotalLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TotalLabel1.setText("LIST BELANJA :");
        TotalLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BackGround.add(TotalLabel1);
        TotalLabel1.setBounds(250, 90, 200, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nama Produk", "Jenis", "Satuan", "Harga", "Jumlah", "Total"
            }
        ));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(5);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(30);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(20);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(20);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(30);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(10);
        }

        BackGround.add(jScrollPane1);
        jScrollPane1.setBounds(250, 130, 1090, 350);

        txtbill.setColumns(20);
        txtbill.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        txtbill.setRows(5);
        jScrollPane2.setViewportView(txtbill);

        BackGround.add(jScrollPane2);
        jScrollPane2.setBounds(520, 500, 330, 200);

        HapusLabel.setBackground(new java.awt.Color(51, 0, 97));
        HapusLabel.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        HapusLabel.setForeground(new java.awt.Color(255, 255, 255));
        HapusLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HapusLabel.setText("HAPUS");
        HapusLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(242, 37, 200), 2, true));
        HapusLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HapusLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        HapusLabel.setOpaque(true);
        HapusLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HapusLabelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HapusLabelMouseExited(evt);
            }
        });
        BackGround.add(HapusLabel);
        HapusLabel.setBounds(860, 640, 150, 60);

        JualLabel.setBackground(new java.awt.Color(51, 0, 97));
        JualLabel.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        JualLabel.setForeground(new java.awt.Color(255, 255, 255));
        JualLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JualLabel.setText("JUAL");
        JualLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(242, 37, 200), 2, true));
        JualLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JualLabel.setOpaque(true);
        JualLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JualLabelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JualLabelMouseExited(evt);
            }
        });
        BackGround.add(JualLabel);
        JualLabel.setBounds(860, 500, 150, 60);

        CetakStrukLabel.setBackground(new java.awt.Color(51, 0, 97));
        CetakStrukLabel.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        CetakStrukLabel.setForeground(new java.awt.Color(255, 255, 255));
        CetakStrukLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CetakStrukLabel.setText("CETAK STRUK");
        CetakStrukLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(242, 37, 200), 2, true));
        CetakStrukLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CetakStrukLabel.setOpaque(true);
        CetakStrukLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CetakStrukLabelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CetakStrukLabelMouseExited(evt);
            }
        });
        BackGround.add(CetakStrukLabel);
        CetakStrukLabel.setBounds(860, 570, 150, 60);

        TotalLabel.setBackground(new java.awt.Color(255, 255, 255));
        TotalLabel.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        TotalLabel.setForeground(new java.awt.Color(255, 255, 255));
        TotalLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TotalLabel.setText("TOTAL :");
        TotalLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BackGround.add(TotalLabel);
        TotalLabel.setBounds(1010, 490, 120, 30);

        RPLabel.setBackground(new java.awt.Color(255, 255, 255));
        RPLabel.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        RPLabel.setForeground(new java.awt.Color(255, 255, 255));
        RPLabel.setText("RP.");
        BackGround.add(RPLabel);
        RPLabel.setBounds(1140, 490, 50, 30);

        Total2Label.setBackground(new java.awt.Color(255, 255, 255));
        Total2Label.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        Total2Label.setForeground(new java.awt.Color(255, 255, 255));
        BackGround.add(Total2Label);
        Total2Label.setBounds(1190, 490, 170, 30);

        KeluarLabel1.setBackground(new java.awt.Color(51, 0, 97));
        KeluarLabel1.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        KeluarLabel1.setForeground(new java.awt.Color(255, 255, 255));
        KeluarLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        KeluarLabel1.setText("LIHAT PERSEDIAAN");
        KeluarLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(242, 37, 200), 2, true));
        KeluarLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        KeluarLabel1.setOpaque(true);
        KeluarLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KeluarLabel1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                KeluarLabel1MouseExited(evt);
            }
        });
        BackGround.add(KeluarLabel1);
        KeluarLabel1.setBounds(240, 500, 270, 70);

        KeluarLabel.setBackground(new java.awt.Color(51, 0, 97));
        KeluarLabel.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        KeluarLabel.setForeground(new java.awt.Color(255, 255, 255));
        KeluarLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        KeluarLabel.setText("KELUAR");
        KeluarLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(242, 37, 200), 2, true));
        KeluarLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        KeluarLabel.setOpaque(true);
        KeluarLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KeluarLabelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                KeluarLabelMouseExited(evt);
            }
        });
        BackGround.add(KeluarLabel);
        KeluarLabel.setBounds(1140, 640, 200, 60);

        MenuSemuaLabel1.setBackground(new java.awt.Color(51, 0, 97));
        MenuSemuaLabel1.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        MenuSemuaLabel1.setForeground(new java.awt.Color(255, 255, 255));
        MenuSemuaLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MenuSemuaLabel1.setText("?");
        MenuSemuaLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        MenuSemuaLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 37, 200)));
        MenuSemuaLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuSemuaLabel1.setOpaque(true);
        MenuSemuaLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuSemuaLabel1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MenuSemuaLabel1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                MenuSemuaLabel1MouseReleased(evt);
            }
        });
        BackGround.add(MenuSemuaLabel1);
        MenuSemuaLabel1.setBounds(240, 660, 40, 30);

        BackGroundIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/rsz_2680024.jpg"))); // NOI18N
        BackGround.add(BackGroundIcon);
        BackGroundIcon.setBounds(0, 0, 1366, 768);

        getContentPane().add(BackGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 768));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void IdTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdTextFieldActionPerformed

    private void IdTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IdTextFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdTextFieldKeyPressed

    private void IdTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IdTextFieldKeyReleased
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_IdTextFieldKeyReleased

    private void NamaProdukTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaProdukTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamaProdukTextFieldActionPerformed

    private void NamaProdukTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NamaProdukTextFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamaProdukTextFieldKeyPressed

    private void NamaProdukTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NamaProdukTextFieldKeyReleased
        // TODO add your handling code here:
        boolean kunci1 = true;
        boolean kunci2 = false;
        if(!JenisTextField.getText().equalsIgnoreCase("")){
             kunci2 = true;
        }
        cari(kunci1,kunci2);
         
    }//GEN-LAST:event_NamaProdukTextFieldKeyReleased

    private void JenisTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JenisTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JenisTextFieldActionPerformed

    private void JenisTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JenisTextFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JenisTextFieldKeyPressed

    private void JenisTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JenisTextFieldKeyReleased
        // TODO add your handling code here:
        
        boolean kunci1 = false;
        boolean kunci2 = true;
        if(!NamaProdukTextField.getText().equalsIgnoreCase("")){
             kunci1 = true;
        }
        cari(kunci1,kunci2);
        
    }//GEN-LAST:event_JenisTextFieldKeyReleased

    private void HargaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HargaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HargaTextFieldActionPerformed

    private void HargaTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_HargaTextFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_HargaTextFieldKeyPressed

    private void HargaTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_HargaTextFieldKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_HargaTextFieldKeyReleased

    private void SatuanTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SatuanTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SatuanTextFieldActionPerformed

    private void SatuanTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SatuanTextFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_SatuanTextFieldKeyPressed

    private void SatuanTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SatuanTextFieldKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_SatuanTextFieldKeyReleased

    private void TambahKeListLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TambahKeListLabelMouseClicked
        // TODO add your handling code here:
     
    }//GEN-LAST:event_TambahKeListLabelMouseClicked

    private void TambahKeListLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TambahKeListLabelMouseExited
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TambahKeListLabelMouseExited

    private void CetakStrukLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CetakStrukLabelMouseClicked
        // TODO add your handling code here:
        printBill();
    }//GEN-LAST:event_CetakStrukLabelMouseClicked

    private void CetakStrukLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CetakStrukLabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_CetakStrukLabelMouseExited

    private void KeluarLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KeluarLabelMouseClicked
        // TODO add your handling code here:
        dashboard dashB = new dashboard();
        dashB.setVisible(true);
        int state = dashB.getExtendedState();
        state &= ~JFrame.ICONIFIED;
        dashB.setExtendedState(state);
        dashB.setAlwaysOnTop(true);
        dashB.toFront();
        dashB.requestFocus();
        dashB.setAlwaysOnTop(false);
        
        this.dispose();
    }//GEN-LAST:event_KeluarLabelMouseClicked

    private void KeluarLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KeluarLabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_KeluarLabelMouseExited

    private void HapusLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HapusLabelMouseClicked
        // TODO add your handling code here:
        
         int viewIndex = jTable1.getSelectedRow();
            if(viewIndex != -1) {
                int modelIndex = jTable1.convertRowIndexToModel(viewIndex); // converts the row index in the view to the appropriate index in the model
                DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
                model.removeRow(modelIndex);
                JOptionPane.showMessageDialog(null, " List belanja yang anda pilih berhasil dihapus ","Informasi", JOptionPane.INFORMATION_MESSAGE);
            }else {
                JOptionPane.showMessageDialog(null, " Tidak ada list belanja yang dihapus ","Informasi", JOptionPane.INFORMATION_MESSAGE);
            }

    
    }//GEN-LAST:event_HapusLabelMouseClicked

    private void HapusLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HapusLabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_HapusLabelMouseExited

    private void JualLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JualLabelMouseClicked
        // TODO add your handling code here:
        bill();
        dashboard.pil("0");
        if(LPP.isVisible() == true){
             LPP.setVisible(false);
                LPP.dispose();
                LPP = new LihatPersediaan();
                LPP.setVisible(false);
                LPP.dispose();
                LPP.setVisible(true);
                int state = LPP.getExtendedState();
                state &= ~JFrame.ICONIFIED;
                LPP.setExtendedState(state);
                LPP.setAlwaysOnTop(true);
                LPP.toFront();
                LPP.requestFocus();
                LPP.setAlwaysOnTop(false);
        }
               
                
        
    }//GEN-LAST:event_JualLabelMouseClicked

    private void JualLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JualLabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_JualLabelMouseExited

    private void TambahKeListLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TambahKeListLabelMousePressed
        // TODO add your handling code here:
               
           tambahList();

    }//GEN-LAST:event_TambahKeListLabelMousePressed

    private void TambahKeListLabelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TambahKeListLabelMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_TambahKeListLabelMouseReleased

    private void KeluarLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KeluarLabel1MouseClicked
        // TODO add your handling code here:
        dashboard.pil("0");
                
                
                LPP.setVisible(false);
                LPP.dispose();
                LPP = new LihatPersediaan();
                LPP.setVisible(true);
                int state = LPP.getExtendedState();
                state &= ~JFrame.ICONIFIED;
                LPP.setExtendedState(state);
                LPP.setAlwaysOnTop(true);
                LPP.toFront();
                LPP.requestFocus();
                LPP.setAlwaysOnTop(false);
                //this.dispose();
    }//GEN-LAST:event_KeluarLabel1MouseClicked

    private void KeluarLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KeluarLabel1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_KeluarLabel1MouseExited

    private void JumlahTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JumlahTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JumlahTextFieldActionPerformed

    private void JumlahTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JumlahTextFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JumlahTextFieldKeyPressed

    private void JumlahTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JumlahTextFieldKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_JumlahTextFieldKeyReleased

    private void MenuSemuaLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuSemuaLabel1MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "* Input Nama Produk dan Jenis dari Produk Dengan Benar ( Tekan Tombol Persediaan Untuk Melihat Persediaan Yang Ada )\n\n"
                                          + "* Tentukan Jumlah yang Ingin Dibeli Per Satuan Gram atau Pack Tergantung Produknya\n\n"
                                          + "* Pilih List Belanja Yang Mau Dihapus dan Tekan Tombol \"TAMBAH KE LIST\" Untuk Menambahkannya Ke Daftar Belanja\n\n"
                                          + "* Sebelum Menekan Tombol \"Jual\", Tekan Tombol \"HAPUS\" Untuk Menghapus List Yang Salah\n\n"
                                          + "* Tekan Tombol \"JUAL\" Untuk Menjual Produk Yang Sudah Ada Di List Belanja dan Mengupdate Persediaan Yang Sudah Dijual Ke DataBase\n\n"
                                          + "* Tekan Tombol \"CETAK STRUK\" Untuk Mencetak Struk Ke Printer Sesuai Apa Yang Di Jual\n\n" ,"Informasi", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_MenuSemuaLabel1MouseClicked

    private void MenuSemuaLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuSemuaLabel1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuSemuaLabel1MousePressed

    private void MenuSemuaLabel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuSemuaLabel1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuSemuaLabel1MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelKasir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackGround;
    private javax.swing.JLabel BackGroundIcon;
    private javax.swing.JLabel CetakStrukLabel;
    private javax.swing.JLabel HapusLabel;
    private javax.swing.JLabel HargaLabel;
    public static final javax.swing.JTextField HargaTextField = new javax.swing.JTextField();
    private javax.swing.JLabel IdLabel;
    public static final javax.swing.JTextField IdTextField = new javax.swing.JTextField();
    private javax.swing.JLabel JenisLabel;
    public static final javax.swing.JTextField JenisTextField = new javax.swing.JTextField();
    private javax.swing.JLabel JualLabel;
    private javax.swing.JLabel JudulLabel1;
    private javax.swing.JLabel JudulLabel2;
    private javax.swing.JLabel JumlahLabel;
    public static final javax.swing.JTextField JumlahTextField = new javax.swing.JTextField();
    private javax.swing.JLabel KeluarLabel;
    private javax.swing.JLabel KeluarLabel1;
    private javax.swing.JLabel Logo;
    private javax.swing.JPanel MenuPanel;
    private javax.swing.JLabel MenuSemuaLabel1;
    private javax.swing.JLabel NamaProdukLabel;
    public static final javax.swing.JTextField NamaProdukTextField = new javax.swing.JTextField();
    private javax.swing.JLabel RPLabel;
    private javax.swing.JLabel SatuanLabel;
    public static final javax.swing.JTextField SatuanTextField = new javax.swing.JTextField();
    private javax.swing.JLabel TambahKeListLabel;
    private javax.swing.JLabel Total2Label;
    private javax.swing.JLabel TotalLabel;
    private javax.swing.JLabel TotalLabel1;
    private javax.swing.JLabel TotalLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea txtbill;
    // End of variables declaration//GEN-END:variables
}
